### ISSUE TITLE
Feature request for Qt version

### ISSUE THREAD

**Issue by pablomartan** [gm-vm/openfortivpn-webview#23]
Hello!

I am trying to use the qt version of this wonderful software to connect to my company's VPN, but there's no obvious option to trust the certificate as there is on the electron version. The reason for using the qt version is that I'm also trying to package this software for the `guix` package manager and using electron adds some unwanted overhead.

I have no experience on C++ or QT programming, but I could try to modify the source if needed.

Any guidance on this issue would be greatly appreciated.

**Comment by gm-vm** [comment]
Are you talking about `--extra-ca-certs`, `--trusted-cert` or both?

I looked quickly at the documentation having something that works like `--trusted-cert` should be rather simple, but I have to look a bit more for the other option.

**Comment by pablomartan** [comment]
Hi, I meant `--trusted-cert` 👌

**Comment by gm-vm** [comment]
I added support for both: 
- https://github.com/gm-vm/openfortivpn-webview/commit/2da13131c910daa4ffd8c44a71654c8cc3ba7366
- https://github.com/gm-vm/openfortivpn-webview/commit/0ce1a4f9f3bbb416b170658773b3f450cab50043

**Comment by pablomartan** [comment]
Thank you very much!
