### ISSUE TITLE
How to use with openfortivpn?

### ISSUE THREAD

**Issue by HappiePlant** [gm-vm/openfortivpn-webview#25]
Sorry for the inconvenience, but I'm not sure how to use this program with openfortivpn. I installed it on Linux and I get the cookie, but I don't know what to do with it :)
Thank you.

**Comment by gm-vm** [comment]
`openfortivpn-webview` simply outputs the `SVPN_COOKIE` needed by `openfortivpn` to establish the connection. The most convenient way to pass the cookie is by piping the output in this way:

```sh
openfortivpn-webview YOUR_VPN_GATEWAY | sudo openfortivpn --cookie-on-stdin YOU_VPN_GATEWAY
```

**Comment by edmundlaugasson** [comment]
Still cannot connect:
./openfortivpn-webview-1.2.3-x86_64.AppImage vpn.myserver.com:443 | sudo openfortivpn vpn.myserver.com:443 --cookie-on-stdin --saml-login
It opens quickly window and closes it as I were authenticated already. Then still openfortivpn waiting for authentication at https://vpn.myserver.com:443/remote/saml/start?redirect=1

Tried also `--keep-open`, also `--disable-gpu`, `--no-sandbox` with `openfortivpn-webview` - didn't help either.

**Comment by gm-vm** [comment]
You have to either use `--cokie-on-stdin` or `--saml-login`, not both.

`--saml-login` is the new kid in town and it uses a different mechanism for the authentication. This application is for `--cookie-on-stdin`.

`openfortivpn` should probably error out when trying to use both the options at the same time.
