### ISSUE TITLE
WebKitGTK version?

### ISSUE THREAD

**Issue by ericonr** [gm-vm/openfortivpn-webview#31]
Hi!

Thank you for developing this :)

I use Fortinet with authentication over Duo, and I wasn't able to reach Duo's 2FA prompt with the qt6-webview client. I haven't tried the electron version, which I'd rather avoid, but I saw in [one of your comments](https://github.com/adrienverge/openfortivpn/issues/867#issuecomment-1120427315) that you had a python script using WebKitGTK, which worked better with Duo. Do you still have that script? Would you be open to including that script in this repository, or just providing it some other way?

That said, my login flow didn't directly get access to SVPNCOOKIE, because after login there was a redirection to `127.0.0.1:8020`, with an ID to be passed to another URL under my VPN's domain, which finally contained the SVPNCOOKIE. That flow is implemented in https://github.com/filippor/XdgOpenSaml/blob/main/XdgOpenSaml.java . Would you be interested in including something similar in this project? I might be able to contribute one in either C++ or Python. I have no idea how to best determine if that sort of workaround is needed, though.

**Comment by gm-vm** [comment]
That script is long gone, but it was something I put together hacking some script I found somewhere on the internet.

Anyway, you are probably better off using this (from the same author): https://github.com/adrienverge/openfortivpn/pull/1217. It implements the flow you describe and let's you use any browser.

**Comment by ericonr** [comment]
I was actually interested in using the obtained cookie in OpenConnect, so a solution in openfortivpn itself doesn't apply for me. Thanks for the suggestion, though!

OpenConnect has the advantage of being able to run as non-root, so implementing that functionality there would be less problematic, but still not ideal, IMO. I think composing the tools so the specific code doesn't have to be included in every single implementation is best. 

I will see if I can cook something up in python myself, then. And I will be closing this issue.

Thank you again!
