### ISSUE TITLE
I can’t get the cookie

### ISSUE THREAD

**Issue by M4rotte** [gm-vm/openfortivpn-webview#33]
Hi,

I can get to the login page, enter my credential, then it asks for a token I can provide, but in the end I don’t get the cookie:

```
$ ./openfortivpn-webview vpngw.foo.com:443/HMS --extra-ca-certs /etc/openfortivpn/cert/ca.pem 
qt.webenginecontext: 

GL Type: desktop
Surface Type: OpenGL
Surface Profile: CompatibilityProfile
Surface Version: 4.6
QSG RHI Backend: OpenGL
Using Supported QSG Backend: yes
Using Software Dynamic GL: no
Using Multithreaded OpenGL: yes

Init Parameters:
  *  application-name openfortivpn-webview 
  *  browser-subprocess-path /usr/lib/qt6/libexec/QtWebEngineProcess 
  *  create-default-gl-context  
  *  disable-features ConsolidatedMovementXY,InstalledApp,BackgroundFetch,WebOTP,WebPayments,WebUSB,PictureInPicture 
  *  disable-setuid-sandbox  
  *  disable-speech-api  
  *  enable-features NetworkServiceInProcess,TracingServiceInProcess 
  *  enable-threaded-compositing  
  *  in-process-gpu  
  *  use-gl desktop 

webview: "https://vpngw.foo.com:443/HMS/remote/saml/start"
webview: "https://vpngw.foo.com/HMS/remote/saml/start"
webview: "https://vpngw.foo.com/remote/login?lang=en"
js: Refused to apply style from 'https://vpngw.foo.com/css/main-blue.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
js: Uncaught TypeError: Cannot read properties of null (reading 'style')
webview: "https://vpngw.foo.com/remote/login?&err=sslvpn_login_permission_denied&lang=en"
js: Refused to apply style from 'https://vpngw.foo.com/css/main-blue.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
js: Uncaught TypeError: Cannot read properties of null (reading 'style')
```

Any idea of what I’ve done wrong?

PS: I have a Windows 10 host with FortiClient from which I got the CAs, is there any other info I’d need to get from there?

**Comment by gm-vm** [comment]
The application does nothing more than starting a browser and monitor all the cookies until it finds one named `SVPN_COOKIE`. You could really just browse to `https://vpngw.foo.com:443/HMS/remote/saml/start` with any browser.

Is the page loading? Could it be that `HMS` is the realm (`openfortivpn-webview vpngw.foo.com:443 --realm=HMS`) rather than a path?

**Comment by M4rotte** [comment]
> Is the page loading? Could it be that `HMS` is the realm (`openfortivpn-webview vpngw.foo.com:443 --realm=HMS`) rather than a path?

I don’t know whats the realm means in this context, I’ll that and tell you.

**Comment by gm-vm** [comment]
As I mentioned in my previous message there really isn't much I can do here, the application is just a browser that monitors the cookies until it finds one named `SVPN_COOKIE`.

You can also try to do some remote debugging to see what is going on: pass `--remote-debugging-port=9222 --remote-allow-origins=http://localhost:9222` to the application and then visit `http://localhost:9222` with a Chromium based browser to inspect the page.
