### ISSUE TITLE
Noob question

### ISSUE THREAD

**Issue by lfariasrj** [gm-vm/openfortivpn-webview#36]
Hi Folks,

I downloaded .AppImage but this app not started on my ubuntu arm.
I downloaded .tar, extract but when I run openfortivpn-webview --url ´foo´, I receive:

./openfortivpn-webview --url 'https://url:port/sso'
zsh: exec format error: ./openfortivpn-webview

openfortivpn-webview --url 'https://url:port/sso'
zsh: command not found: openfortivpn-webview

Whats my mistakes?

**Comment by gm-vm** [comment]
Check [v1.2.2-electron](https://github.com/gm-vm/openfortivpn-webview/releases/tag/v1.2.2-electron), which I've just released.

Previous releases were only built for x86_64, that's why it was not working for you. Luckily for me electron-builder allows to cross-compile for arm, so I just had to tell it to do it.

Disclaimer: I did not try the arm executable, but I expect it to work.

**Comment by lfariasrj** [comment]
Thanks for your fast response.

I Downloaded the new version 1.2.2-arm64.
I can connect on my server but don't receive tunnel IP and navigation doesn't work fine.


/openfortivpn-webview-1.2.2-arm64.AppImage --url 'https://url:port/sso' --keep-open
[17121:0930/172349.943113:ERROR:viz_main_impl.cc(196)] Exiting GPU process due to errors during initialization
https://vpn.rd.com.br:10443/sso
[17152:0930/172350.243613:ERROR:viz_main_impl.cc(196)] Exiting GPU process due to errors during initialization
[17151:0930/172350.575213:ERROR:command_buffer_proxy_impl.cc(127)] ContextResult::kTransientFailure: Failed to send GpuControl.CreateCommandBuffer.
about:blank
https://url:port/remote/saml/start?realm=sso
https://url/saml-idp/sso/login/?SAMLRequest=token
https://url/saml-idp/login_process/?continue=1
https://url:port/remote/saml/login/
https://url:port/remote/loginconfirm
https://url:port/remote/loginconfirm?action=login
https://url:port/sslvpn/portal.html
SVPNCOOKIE=cookie
about:blank
https://url:port/sslvpn/portal.html#!/
SVPNCOOKIE=cookie

Best Regards,

**Comment by gm-vm** [comment]
The error tells me there are problems with the GPU. I can only suggest the use of `--disable-gpu`, which you can pass to the application.

**Comment by lfariasrj** [comment]
Ok,
No more issues...

But, where do I set SVPNCOOKIE on openfortivpn?

I first understood that openfortivpn-webview substitutes an openfortivpn, however I need to use both.

**Comment by gm-vm** [comment]
https://github.com/gm-vm/openfortivpn-webview/issues/25
