### ISSUE TITLE
Weird error, how to debug?

### ISSUE THREAD

**Issue by smktpd** [gm-vm/openfortivpn-webview#39]
`openfortivpn-webview vpn.mycompany.tld:44333`
->
```
openfortivpn-webview[22249:721491] WARNING: Secure coding is automatically enabled for restorable state! However, not on all supported macOS versions of this application. Opt-in to secure coding explicitly by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState:.
https://vpn.mycompany.tld:44333/remote/saml/start
(node:22249) electron: Failed to load URL: https://vpn.mycompany.tld:44333/remote/saml/start with error: ERR_PROXY_CONNECTION_FAILED
(Use `openfortivpn-webview --trace-warnings ...` to show where the warning was created)
[22250:1004/153202.500749:ERROR:display.cc(299)] Frame latency is negative: -0.443 ms
```
`openfortivpn-webview --trace-warnings vpn.mycompany.tld:44333` just returns help, meaning that the binary doesn't support key `--trace-warnings`

macOS ver: 14.6 (23G80)
That used to work, but now it has stopped (I don't know what changed).
It happened to me on 1.2.0 version of openfortivpn-webview, but now I've updated to the latest release (1.2.2) and it still reproduces.
Our fortivpn uses a keycloak server as an auth realm. A regular browser when opening https://vpn.mycompany.tld:44333/ redirects me to https://sso.mycompany.tld/ where I am prompted by keycloak for my login+pass. I even sniffed SVPNCOOKIE cookie from the browser's session to successfully log into VPN using `openfortivpn`.

**Comment by gm-vm** [comment]
Try to change the order of the arguments (I think this should be fixed, your invocation should be valid IMO):
```
openfortivpn-webview vpn.mycompany.tld:44333 --trace-warnings
```

You can also do this: https://www.chromium.org/for-testers/enable-logging/

PS: if you need to use some proxy you can do [this](https://github.com/gm-vm/openfortivpn-webview?tab=readme-ov-file#proxy-servers).

**Comment by smktpd** [comment]
facepalm.jpg: turns out I indeed had a setting specified on system network level to use http+https proxies pointing to 127.0.0.1:8080, I don't remember why I had this configured.
