### ISSUE TITLE
Hardware security key support

### ISSUE THREAD

**Issue by Cambi0nn** [gm-vm/openfortivpn-webview#42]
I noticed the QT webview doesn't work with hardware security keys like Yubikey, which can be rather inconvenient when that's used for MFA. Any change this can be made to work?

**Comment by gm-vm** [comment]
From what I could see, this should be possible as of Qt 6.7, but the application needs to implement some APIs for that to happen: https://doc.qt.io/qt-6.7/qtwebengine-webenginewidgets-simplebrowser-example.html#managing-webauth-fido-ux-requests

**Comment by gm-vm** [comment]
There is an example that I copied mostly as is. I pushed it to https://github.com/gm-vm/openfortivpn-webview/tree/fido
I have no way to test this, unless I figure out a way to simulate the authentication, so I don't know what to expect and I don't even know if it works.

**Comment by gm-vm** [comment]
I guess no one pays attention to tags... I created a release from tag v1.3.0-qt, which has been there for quite a while now.
