### ISSUE TITLE
Add support Wayland

### ISSUE THREAD

**Issue by CRAG666** [gm-vm/openfortivpn-webview#5]
Your project is incredible, has saved my life.I would like to support Wayland for functions natively if the X server

**Comment by gm-vm** [comment]
I don't think there is anything to do for that here, both Qt and Electron should support Wayland out of the box.

I haven't tried it personally, but from what I can see, you need to pass special arguments or set env variables:

```sh
# For the Electron based application
openfortivpn-webview --enable-features=UseOzonePlatform --ozone-platform=wayland

# For the Qt based application
QT_QPA_PLATFORM=wayland openfortivpn-webview
```

**Comment by gm-vm** [comment]
Closing this since I don't think there is anything for me to do.
